### ISSUE TITLE
Memory overflow for format(0, 18, 3)

### ISSUE THREAD

**Issue by benaadams** [devtooligan/solpretty#8]
format(0, 18, 3)

gives

[FAIL. Reason: Memory allocation overflow]

**Comment by devtooligan** [comment]
thanks for reporting this! i'll check it out soon

**Comment by benaadams** [comment]
Was trying to get it to do leading zeros on decimals e.g. 0.5 but that didn't seem to work either

**Comment by devtooligan** [comment]
I've got it set up now so that it should at least be able to handle 0 as "0.00"

lemme know if this fixes it for you! 

https://github.com/devtooligan/solpretty/blob/95af374f11c6d24d07159f0d38a68fa4fbdb9b7e/test/SolPretty.t.sol#L22-L42

**Comment by devtooligan** [comment]
closing , reopen if need be
